# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Momodou B Jallow
author: mbjallow
logo: images/luka.jpg
only_build_toc_files: false


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/mbjallow6/mbjallow6  # Online location of your book
  path_to_book: root  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# configure binder links 


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
